#!/bin/bash

# Extract Pokémon Data Script
# Uses jq, awk, and sed to extract and format Pokémon information

# Extract data using jq and format with awk and sed
jq -r '.name, .height, .weight, .types[0].type.name' data.json | \
awk 'NR==1 {name=$0} 
     NR==2 {height=$0/10} 
     NR==3 {weight=$0/10} 
     NR==4 {type=$0} 
     END {print toupper(substr(name,1,1)) substr(name,2) " is of type " toupper(substr(type,1,1)) substr(type,2) ", weighs " weight "kg, and is " height "m tall."}' 